M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Thu 17 Aug 2023 06:16:18 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-17T18:16:18-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.1575
%
G90
G05
T1
X2.7559Y-2.3622
X2.7559Y-5.9055
X4.526Y-4.1407
X6.2992Y-2.3622
X6.2992Y-5.9055
T2
X4.5124Y-4.4224
T0
M30
