M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Thu 17 Aug 2023 05:39:02 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-17T17:39:02-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.5276Y-6.0512
T2
X2.7559Y-2.3622
X2.7559Y-5.9055
X6.2992Y-2.3622
X6.2992Y-5.9055
T0
M30
